//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4959
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true)]
[XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class response {
    
    private responseStream streamField;
    
    /// <remarks/>
    public responseStream stream {
        get {
            return this.streamField;
        }
        set {
            this.streamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class responseStream {
    
    private string streamnameField;
    
    private string streamdescriptionField;
    
    private string gametypeField;
    
    private string streamlinkField;
    
    private string embedcodeField;
    
    private bool onlineField;
    
    private string thumbnailField;
    
    private ushort viewerField;
    
    private ushort idField;
    
    /// <remarks/>
    public string streamname {
        get {
            return this.streamnameField;
        }
        set {
            this.streamnameField = value;
        }
    }
    
    /// <remarks/>
    public string streamdescription {
        get {
            return this.streamdescriptionField;
        }
        set {
            this.streamdescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string gametype {
        get {
            return this.gametypeField;
        }
        set {
            this.gametypeField = value;
        }
    }
    
    /// <remarks/>
    public string streamlink {
        get {
            return this.streamlinkField;
        }
        set {
            this.streamlinkField = value;
        }
    }
    
    /// <remarks/>
    public string embedcode {
        get {
            return this.embedcodeField;
        }
        set {
            this.embedcodeField = value;
        }
    }
    
    /// <remarks/>
    public bool online {
        get {
            return this.onlineField;
        }
        set {
            this.onlineField = value;
        }
    }
    
    /// <remarks/>
    public string thumbnail {
        get {
            return this.thumbnailField;
        }
        set {
            this.thumbnailField = value;
        }
    }
    
    /// <remarks/>
    public ushort viewer {
        get {
            return this.viewerField;
        }
        set {
            this.viewerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
