//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4959
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class streams {
    
    private streamsStream streamField;
    
    /// <remarks/>
    public streamsStream stream {
        get {
            return this.streamField;
        }
        set {
            this.streamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStream {
    
    private string subcategoryField;
    
    private string stream_typeField;
    
    private string broadcast_partField;
    
    private string featuredField;
    
    private string channel_subscriptionField;
    
    private string audio_codecField;
    
    private string idField;
    
    private string categoryField;
    
    private string titleField;
    
    private string stats_emailField;
    
    private ushort video_heightField;
    
    private string instant_replicateField;
    
    private string recorderField;
    
    private string site_countField;
    
    private string embed_enabledField;
    
    private string up_timeField;
    
    private string filtered_onField;
    
    private string meta_gameField;
    
    private string formatField;
    
    private string channel_countField;
    
    private string embed_countField;
    
    private string abuse_reportedField;
    
    private string video_codecField;
    
    private string directory_hiddenField;
    
    private string video_widthField;
    
    private string geoField;
    
    private string embed_ratioField;
    
    private string nameField;
    
    private string languageField;
    
    private string stream_countField;
    
    private string video_bitrateField;
    
    private string persistentField;
    
    private streamsStreamChannel channelField;
    
    private string broadcasterField;
    
    private string updated_onField;
    
    private string channel_view_countField;
    
    /// <remarks/>
    public string subcategory {
        get {
            return this.subcategoryField;
        }
        set {
            this.subcategoryField = value;
        }
    }
    
    /// <remarks/>
    public string stream_type {
        get {
            return this.stream_typeField;
        }
        set {
            this.stream_typeField = value;
        }
    }
    
    /// <remarks/>
    public string broadcast_part {
        get {
            return this.broadcast_partField;
        }
        set {
            this.broadcast_partField = value;
        }
    }
    
    /// <remarks/>
    public string featured {
        get {
            return this.featuredField;
        }
        set {
            this.featuredField = value;
        }
    }
    
    /// <remarks/>
    public string channel_subscription {
        get {
            return this.channel_subscriptionField;
        }
        set {
            this.channel_subscriptionField = value;
        }
    }
    
    /// <remarks/>
    public string audio_codec {
        get {
            return this.audio_codecField;
        }
        set {
            this.audio_codecField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string stats_email {
        get {
            return this.stats_emailField;
        }
        set {
            this.stats_emailField = value;
        }
    }
    
    /// <remarks/>
    public ushort video_height {
        get {
            return this.video_heightField;
        }
        set {
            this.video_heightField = value;
        }
    }
    
    /// <remarks/>
    public string instant_replicate {
        get {
            return this.instant_replicateField;
        }
        set {
            this.instant_replicateField = value;
        }
    }
    
    /// <remarks/>
    public string recorder {
        get {
            return this.recorderField;
        }
        set {
            this.recorderField = value;
        }
    }
    
    /// <remarks/>
    public string site_count {
        get {
            return this.site_countField;
        }
        set {
            this.site_countField = value;
        }
    }
    
    /// <remarks/>
    public string embed_enabled {
        get {
            return this.embed_enabledField;
        }
        set {
            this.embed_enabledField = value;
        }
    }
    
    /// <remarks/>
    public string up_time {
        get {
            return this.up_timeField;
        }
        set {
            this.up_timeField = value;
        }
    }
    
    /// <remarks/>
    public string filtered_on {
        get {
            return this.filtered_onField;
        }
        set {
            this.filtered_onField = value;
        }
    }
    
    /// <remarks/>
    public string meta_game {
        get {
            return this.meta_gameField;
        }
        set {
            this.meta_gameField = value;
        }
    }
    
    /// <remarks/>
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public string channel_count {
        get {
            return this.channel_countField;
        }
        set {
            this.channel_countField = value;
        }
    }
    
    /// <remarks/>
    public string embed_count {
        get {
            return this.embed_countField;
        }
        set {
            this.embed_countField = value;
        }
    }
    
    /// <remarks/>
    public string abuse_reported {
        get {
            return this.abuse_reportedField;
        }
        set {
            this.abuse_reportedField = value;
        }
    }
    
    /// <remarks/>
    public string video_codec {
        get {
            return this.video_codecField;
        }
        set {
            this.video_codecField = value;
        }
    }
    
    /// <remarks/>
    public string directory_hidden {
        get {
            return this.directory_hiddenField;
        }
        set {
            this.directory_hiddenField = value;
        }
    }
    
    /// <remarks/>
    public string video_width {
        get {
            return this.video_widthField;
        }
        set {
            this.video_widthField = value;
        }
    }
    
    /// <remarks/>
    public string geo {
        get {
            return this.geoField;
        }
        set {
            this.geoField = value;
        }
    }
    
    /// <remarks/>
    public string embed_ratio {
        get {
            return this.embed_ratioField;
        }
        set {
            this.embed_ratioField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string stream_count {
        get {
            return this.stream_countField;
        }
        set {
            this.stream_countField = value;
        }
    }
    
    /// <remarks/>
    public string video_bitrate {
        get {
            return this.video_bitrateField;
        }
        set {
            this.video_bitrateField = value;
        }
    }
    
    /// <remarks/>
    public string persistent {
        get {
            return this.persistentField;
        }
        set {
            this.persistentField = value;
        }
    }
    
    /// <remarks/>
    public streamsStreamChannel channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
    
    /// <remarks/>
    public string broadcaster {
        get {
            return this.broadcasterField;
        }
        set {
            this.broadcasterField = value;
        }
    }
    
    /// <remarks/>
    public string updated_on {
        get {
            return this.updated_onField;
        }
        set {
            this.updated_onField = value;
        }
    }
    
    /// <remarks/>
    public string channel_view_count {
        get {
            return this.channel_view_countField;
        }
        set {
            this.channel_view_countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStreamID {
    
    private string hrefField;
    
    private uint valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public uint Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStreamName {
    
    private string hrefField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStreamChannel {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("category_title", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("channel_url", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("embed_code", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("embed_enabled", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("id", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image_url_huge", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image_url_large", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image_url_medium", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image_url_small", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image_url_tiny", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("login", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mature", typeof(streamsStreamChannelMature))]
    [System.Xml.Serialization.XmlElementAttribute("producer", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("screen_cap_url_huge", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("screen_cap_url_large", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("screen_cap_url_medium", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("screen_cap_url_small", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("status", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("subcategory", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("subcategory_title", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("tags", typeof(streamsStreamChannelTags))]
    [System.Xml.Serialization.XmlElementAttribute("timezone", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("views_count", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStreamChannelMature {
    
    private bool nilField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool nil {
        get {
            return this.nilField;
        }
        set {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class streamsStreamChannelTags {
    
    private bool nilField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool nil {
        get {
            return this.nilField;
        }
        set {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    category,
    
    /// <remarks/>
    category_title,
    
    /// <remarks/>
    channel_url,
    
    /// <remarks/>
    embed_code,
    
    /// <remarks/>
    embed_enabled,
    
    /// <remarks/>
    id,
    
    /// <remarks/>
    image_url_huge,
    
    /// <remarks/>
    image_url_large,
    
    /// <remarks/>
    image_url_medium,
    
    /// <remarks/>
    image_url_small,
    
    /// <remarks/>
    image_url_tiny,
    
    /// <remarks/>
    language,
    
    /// <remarks/>
    login,
    
    /// <remarks/>
    mature,
    
    /// <remarks/>
    producer,
    
    /// <remarks/>
    screen_cap_url_huge,
    
    /// <remarks/>
    screen_cap_url_large,
    
    /// <remarks/>
    screen_cap_url_medium,
    
    /// <remarks/>
    screen_cap_url_small,
    
    /// <remarks/>
    status,
    
    /// <remarks/>
    subcategory,
    
    /// <remarks/>
    subcategory_title,
    
    /// <remarks/>
    tags,
    
    /// <remarks/>
    timezone,
    
    /// <remarks/>
    title,
    
    /// <remarks/>
    views_count,
}
