//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4959
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class own3dReply {
    
    private own3dReplyLiveEvent liveEventField;
    
    /// <remarks/>
    public own3dReplyLiveEvent liveEvent {
        get {
            return this.liveEventField;
        }
        set {
            this.liveEventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class own3dReplyLiveEvent {
    
    private bool isLiveField;
    
    private ushort liveViewersField;
    
    private ushort liveDurationField;
    
    /// <remarks/>
    public bool isLive {
        get {
            return this.isLiveField;
        }
        set {
            this.isLiveField = value;
        }
    }
    
    /// <remarks/>
    public ushort liveViewers {
        get {
            return this.liveViewersField;
        }
        set {
            this.liveViewersField = value;
        }
    }
    
    /// <remarks/>
    public ushort liveDuration {
        get {
            return this.liveDurationField;
        }
        set {
            this.liveDurationField = value;
        }
    }
}
