//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamNotifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamNotifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a stream name and an ID!.
        /// </summary>
        internal static string AddStreamMessageBoxEnterError {
            get {
                return ResourceManager.GetString("AddStreamMessageBoxEnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already captured!.
        /// </summary>
        internal static string alreadyCapturedMessage {
            get {
                return ResourceManager.GetString("alreadyCapturedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant recognize that stream!.
        /// </summary>
        internal static string cantRecognizeStreamMessage {
            get {
                return ResourceManager.GetString("cantRecognizeStreamMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.justin.tv/api/stream/list.xml?channel=.
        /// </summary>
        internal static string justinTVAPIURL {
            get {
                return ResourceManager.GetString("justinTVAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://justin.tv/.
        /// </summary>
        internal static string justinTVURL {
            get {
                return ResourceManager.GetString("justinTVURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.justin.tv/.
        /// </summary>
        internal static string justinTVURL2 {
            get {
                return ResourceManager.GetString("justinTVURL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text found in clipboard!.
        /// </summary>
        internal static string MainHandler_ClipboardMenuItemClick_No_text_found_in_clipboard_ {
            get {
                return ResourceManager.GetString("MainHandler_ClipboardMenuItemClick_No_text_found_in_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL found in clipboard!.
        /// </summary>
        internal static string MainHandler_ClipboardMenuItemClick_No_URL_found_in_clipboard_ {
            get {
                return ResourceManager.GetString("MainHandler_ClipboardMenuItemClick_No_URL_found_in_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  streams online!.
        /// </summary>
        internal static string MainHandler_UpdateStreamsUI__streams_online_ {
            get {
                return ResourceManager.GetString("MainHandler_UpdateStreamsUI__streams_online_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New stream from clipboard.
        /// </summary>
        internal static string newStreamFromCLMessage {
            get {
                return ResourceManager.GetString("newStreamFromCLMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap online {
            get {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is online!.
        /// </summary>
        internal static string onlineMessage {
            get {
                return ResourceManager.GetString("onlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.own3d.tv/liveCheck.php?live_id=.
        /// </summary>
        internal static string own3dTVAPIURL {
            get {
                return ResourceManager.GetString("own3dTVAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.own3d.tv/live/.
        /// </summary>
        internal static string own3dTVURL {
            get {
                return ResourceManager.GetString("own3dTVURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error.
        /// </summary>
        internal static string parseErrorTitle {
            get {
                return ResourceManager.GetString("parseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamNotifier.
        /// </summary>
        internal static string programmTitle {
            get {
                return ResourceManager.GetString("programmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.regame.tv/liveview_xml_multiple.php?stream_ids=.
        /// </summary>
        internal static string regameTVAPIURL {
            get {
                return ResourceManager.GetString("regameTVAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.regame.tv/live/.
        /// </summary>
        internal static string regameTVURL {
            get {
                return ResourceManager.GetString("regameTVURL", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ringin {
            get {
                return ResourceManager.GetStream("ringin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a stream!.
        /// </summary>
        internal static string selectAStreamMessage {
            get {
                return ResourceManager.GetString("selectAStreamMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsMessage {
            get {
                return ResourceManager.GetString("settingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.justin.tv/identifier http://twitch.tv/identifier  http://www.own3d.tv/live/identifier/name http://regame.tv/live/identifier.
        /// </summary>
        internal static string SupportedStreamsTT {
            get {
                return ResourceManager.GetString("SupportedStreamsTT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon tray_icon_icon {
            get {
                object obj = ResourceManager.GetObject("tray_icon_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateMessage {
            get {
                return ResourceManager.GetString("updateMessage", resourceCulture);
            }
        }
    }
}
